// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyWcnGfBWP47QmxnXrgfWO4FQ584kt-7s',
    appId: '1:467761844659:web:34b0717caf613d85c8bbc6',
    messagingSenderId: '467761844659',
    projectId: 'recipe-app-9ee02',
    authDomain: 'recipe-app-9ee02.firebaseapp.com',
    databaseURL: 'https://recipe-app-9ee02-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-9ee02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhw3WWmUII0dhvN98PsksZfULwdtTunZM',
    appId: '1:467761844659:android:225092957727abbec8bbc6',
    messagingSenderId: '467761844659',
    projectId: 'recipe-app-9ee02',
    databaseURL: 'https://recipe-app-9ee02-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-9ee02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSu3EQL37UmmdC_tlD4sEPbZ1G9JJJAGk',
    appId: '1:467761844659:ios:24ac9c2db1be7ca9c8bbc6',
    messagingSenderId: '467761844659',
    projectId: 'recipe-app-9ee02',
    databaseURL: 'https://recipe-app-9ee02-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-9ee02.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSu3EQL37UmmdC_tlD4sEPbZ1G9JJJAGk',
    appId: '1:467761844659:ios:24ac9c2db1be7ca9c8bbc6',
    messagingSenderId: '467761844659',
    projectId: 'recipe-app-9ee02',
    databaseURL: 'https://recipe-app-9ee02-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-9ee02.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyWcnGfBWP47QmxnXrgfWO4FQ584kt-7s',
    appId: '1:467761844659:web:93cc8301482633c7c8bbc6',
    messagingSenderId: '467761844659',
    projectId: 'recipe-app-9ee02',
    authDomain: 'recipe-app-9ee02.firebaseapp.com',
    databaseURL: 'https://recipe-app-9ee02-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-9ee02.firebasestorage.app',
  );
}
